POST http://localhost:3000/user/
Content-Type: application/json

{
  "login" : "marianek23",
  "password" : "marianek23",
  "email" : "email@gamil.com"
}
###
POST http://localhost:3000/user/info
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377",
  "sex" : "male",
  "weight" : "72",
  "age" : "34",
  "height": "178",
  "levelOfActivity" : {
    "timesPerWeek": "3",
    "tempo": "Moderate" ,
    "trainingType" : "Strength",
    "time": "45"
  },
  "friends" : [{
    "_id" : "610a7baf6e8f5e3184fc0379", 
    "login" : "Leon"}]
}

###
POST http://localhost:3000/user/info/update
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377",
  "sex" : "female",
  "weight" : "57",
  "age" : "23",
  "height": "160",
   "levelOfActivity" : {
    "timesPerWeek": "4",
    "tempo": "Moderate" ,
    "trainingType" : "Strength",
    "time": "90"
  },
  "friends" : [{
    "_id" : "610a7baf6e8f5e3184fc0379", 
    "login" : "Leon"}]
}
###
POST http://localhost:3000/user/info/calories
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377",
  "calories" : "2500"
}
