POST http://localhost:3000/user/
Content-Type: application/json

{
  "login" : "marian",
  "password" : "marian",
  "email" : "email@gamil.com"
}
###
POST http://localhost:3000/user/info
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377",
  "sex" : "male",
  "weight" : "72",
  "age" : "34",
  "height": "178",
  "timesPerWeek": "3",
  "tempo": "Moderate" ,
  "trainingType" : "Strength",
  "time": "1.5",
  "unit": "h",
  "friends" : [{
    "_id" : "610a7baf6e8f5e3184fc0379", 
    "login" : "Leon"}]
}

###
POST http://localhost:3000/user/info/update
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377",
  "sex" : "male",
  "weight" : "76",
  "age" : "23",
  "height": "171",
   "levelOfActivity" : {
    "timesPerWeek": "2",
    "tempo": "Moderate" ,
    "trainingType" : "Strength",
    "time": "90"
  },
  "friends" : [{
    "_id" : "610a7baf6e8f5e3184fc0379", 
    "login" : "Leon"}]
}
###
POST http://localhost:3000/user/info/calories
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377",
  "calories" : "2500"
}

###
GET http://localhost:3000/user/info/get
Content-Type: application/json

{
  "_id" : "610a7baf6e8f5e3184fc0377"
}
